### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by jurgenhaas** [crowdsecurity/php-remediation-engine#13]
Over at the Drupal integration, we've received an issue, that IPv6 is not supported by this package. You can find all the details at https://www.drupal.org/project/crowdsec/issues/3333436

Is there anything we can do on the Drupal integration to make this work, or is IPv6 indeed not supported? If so, are you planning to add IPv6 support in the future?

**Comment by julienloizelet** [comment]
Hi @jurgenhaas,

IPv6 is supported if the scope of the decision is "ip". If the scope is "range", this is not supported (but it should not throw error).

Regarding the error message : 

```
CrowdSec\RemediationEngine\CacheStorage\CacheStorageException: ::1 is not a valid IpV4 address in CrowdSec\RemediationEngine\CacheStorage\AbstractCache->getRangeIntForIp()
```
it was a bug I fixed in the `0.6.0` release of this package : please let me know which version you are using and if using a version >= `0.6.0` solves the issue.

Thanks

**Comment by jurgenhaas** [comment]
@julienloizelet  the 1.0.0-beta3 of the Drupal module uses 0.5.0 - before I can launch another release, we would need a review on this issue first: https://www.drupal.org/project/crowdsec/issues/3333236

**Comment by julienloizelet** [comment]
I guess I can close this issue now.

Thanks
